[project]
name = "ch06-advanced-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eason Wong", email = "hzf510920@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=2.0.0",
]

[project.scripts]
ch06-advanced-servers = "ch06_advanced_servers.server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
